### ISSUE TITLE
Заклинания Жреца появляются и удаляются парами, если дополнительно выбран подкласс 

### ISSUE THREAD

**Issue by Evgenij-Gr** [Etignis/DnD_SpellList_eng_rus#6]
Если выбрать класс Жреца вместе с подклассом Домен Жизни, то в появившемся списке некоторые заклинания будут повторяться дважды. Например, Исцеление Ран: 
![2019-01-10_14-55-16](https://user-images.githubusercontent.com/6704463/50967037-fa3fd900-14e7-11e9-8ab8-87d76127533e.png)
Если попытаться скрыть одно из заклинаний, то скроются оба; закрепляются заклинания, впрочем, по отдельности.

**Comment by Etignis** [comment]
Сейчас каталог заклинаний глобально переделывается, так что в новой версии такого быть не должно.

**Comment by Evgenij-Gr** [comment]
Отлично, спасибо за информацию! И спасибо большое за полезный сайт :)

**Comment by Etignis** [comment]
И вам спасибо за баг-репорт)

**Comment by Etignis** [comment]
Баг исправлен в текущей версии.
